FROM node:alpine
WORKDIR /app/backend
COPY backend/package.json .
RUN npm install
COPY ./backend .
CMD ["npm", "start"]

FROM node:alpine as builder
WORKDIR /app/frontend
COPY frontend/package.json ./
RUN npm install
COPY ./frontend .
CMD ["npm", "start"]